config/routes.rb
  Rails.application.routes.draw do
  
  root 'poem#index'
  get 'luelttettsers'                            => 'poem#luelttettsers'
  get 'rilkittler'                               => 'poem#rilkittler'
  get 'Self-Portrait-in-a-Concave-Mirror'        => 'poem#selfportrait',        as: :selfportrait
  get 'Hot-Network-Questions'                    => 'poem#hotnetworkquestions', as: :hotnetworkquestions
  get 'Western-Birds'                            => 'poem#birds',               as: :birds
  get 'Bread'                                    => 'poem#bread',               as: :bread
  get 'spuilyie'                                 => 'poem#spuilyie'
  get 'The-Sun-The-Moon'                         => 'poem#sunmoon',             as: :sunmoon
  get 'yoloy'                                    => 'poem#yoloy'
  get 'Create-Password'                          => 'poem#createpassword'
  get 'Case-Study-B'                             => 'poem#casestudyb',           as: :casestudyb
  get 'aeiou'                                    => 'poem#aeiou'
  get 'Robopoetics'                              => 'poem#robopoetics',          as: :robopoetics
  get 'We-Can-Just-Check-The-Numbers-Afterwards' => 'poem#checkthenumbersafter', as: :checkthenumbersafter

end

app/models/function_word.rb
class FunctionWord < ActiveRecord::Base
end

app/models/poem.rb
class Poem < ActiveRecord::Base
end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/poem_controller.rb
class PoemController < ApplicationController
  def index
		# RANDOMIZE WORD SELECTION
	if (rand(1..10) >= 8)
	 	@new_word = Word.order("RANDOM()").first.word
	  else
		@new_word = FunctionWord.order("RANDOM()").first.word
	end
	# ADD NEW WORD TO THE LONG POEM
	@newpoem = Poem.last.poetry.split(" ").unshift("#{@new_word}").join(" ")
	Poem.last.update_attributes(poetry: "#{@newpoem}")
	# INSTANTIATE LONG POEM
	@the_LongPoem = Poem.last.poetry.split(" ")
	# PULL OUT FIRST AND FINAL LINES FOR DISPLAY
	@first_left = @the_LongPoem.slice!(0,4)
	@first_right= @the_LongPoem.slice!(0,4)
	@last_right = @the_LongPoem.slice!(-4, 4)
	@last_left  = @the_LongPoem.slice!(-4, 4)
	# ACE RETURNS
	@Ace        = @the_LongPoem.shuffle.each_slice(4).to_a
	flash[:success] = "you've contributed the word: <b><em>#{@new_word}</em></b> ... how poetic ...".html_safe
	
  end
  # POEMS
  def luelttettsers         
  end

  def rilkittler
  end

  def selfportrait
  end

  def hotnetworkquestions
  end

  def birds
  end

  def bread
  end

  def spuilyie
  end

  def sunmoon
  end

  def yoloy 
  end
  
  def createpassword
  end

  def casestudyb
  end

  def aeiou
  end
  

  # ESSAYS

  def robopoetics
  end

  def checkthenumbersafter
  end


  
end

app/helpers/application_helper.rb
module ApplicationHelper


  def full_title(page_title = '')
    base_title = "|||"
    if page_title.empty?
      base_title
    else
      "#{page_title}"
    end
  end

end

app/helpers/poem_helper.rb
module PoemHelper
end

app/views/layouts/_omphalos.html.erb
<section class = "the-center-cannot-hold text-center">
    <svg  xmlns:xlink="http://www.w3.org/1999/xlink" height="140" width="140" class = 'hvr-wobble-skew'>
    <a xlink:href="http://abcdefghijklnmoqprstuvw.xyz">
      <circle id = "periphery" class = "hvr-wobble-skew" cx="55" cy="50" r="40" stroke="#00DDFF" stroke-width="3" fill="white" /> 
        </a>
    </svg>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
 <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,700' rel='stylesheet' type='text/css'>
 <link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
</head>
<body>
<main class="container-fluid">
<%= yield %>
</main>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55771414-10', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/poem/_long_poem.html.erb
<h1 class = "poem-title">
<%= @new_word %>
</h1>
<article class="row">
	<!-- THE LONG POEM -->
<section class="col-md-6  col-sm-6 col-xs-6">	
<!-- PLACE THE FIRST TWO LINES TOGETHER -->
<section class="line-wrapper"> 
		<section class="lefto col-md-6 col-sm-6 col-xs-6">
			<p> <%= @first_left.join(" ") %> </p>
		</section>
		<section class="righty col-md-6 col-sm-6 col-xs-6">
			<p> <%= @first_right.join(" ") %> </p>
		</section>	
	</section>
<!-- PLACE SHUFFLEDPOEM -->
<% @Ace.in_groups_of(2, false) do |shard| %>

	<section class="line-wrapper"> 
		<section class="lefto col-md-6 col-sm-6 col-xs-6">
			<p> <%= shard[0].join(" ") %> </p>
		</section>
		<section class="righty col-md-6 col-sm-6 col-xs-6">
			<p> <%= shard[1].join(" ") if shard[1].present? %> </p>
		</section>
		<br>
	</section>

<% end %>
<!-- PLACE THE LAST LINES TOGETHER -->
<section class="line-wrapper"> 
		<section class="lefto col-md-6 col-sm-6 col-xs-6">
			<p> <%= @last_left.join(" ") %> </p>
		</section>
		<section class="righty col-md-6 col-sm-6 col-xs-6">
			<p> <%= @last_right.join(" ") %> </p>
		</section>	
	</section>
</section>
<!-- END THE LONG POEM..for now -->

app/views/poem/aeiou.html.erb
<% provide(:title, "AEIOU") %>
<%= render 'layouts/omphalos' %>
<!-- About the Poem -->
<article class="close-the-poetic-loop row">
<section class="col-md-6 col-md-offset-3 col-sm-4 col-sm-offset-5 col-xs-8 col-xs-offset-2">
<p>Unlike Christan Bök's <a href="http://archives.chbooks.com/online_books/eunoia/text.html"><em>EUNOIA</em></a>, this poem makes use of every word in the English language containing <em>all</em> the vowels. It is, in this sense, an <em><b>omnivocal lipogram</b></em>. Not the most robust or interesting poem, I suggest it is best skimmed, wherein one hopes to catch a glimpse of some of the perhaps more promising phrases.</p>
</section>
</article>
<!-- The Poem -->
 <section class  = "row aeiou-title">
       <h1 class =  "col-md-offset-2">AEIOU</h1>
</section> 

<article class = "row aeiou">
		<section class="col-md-8 col-md-offset-2">
<p>groundbreaking unimportance</p>
<p>conceptualizing computerization </p>
<p>incommunicable mountainsides mustachioed nefarious</p>
<p>overanxious overcautious plutocracies</p>
<p>Authoritative gesticulations, ejaculations,  expostulations, elucidations  </p>
<p>Gregarious mouthwatering numerological homosexuality molecularity</p>
<p>unobjectionable tambourines</p>
<p>ambidextrous adulteration bureaucratization</p>
<p>soul-searching hallucinogenic inconsequential autobiographies </p>
<p>tongue-lashing tautologies </p>
<p>unemotional persuasion </p>
<p>unsportsmanlike housecleaning</p>
<p>ratatouille housewarming </p>
<p>autopsies
adventitious
mountaineering</p>
<p>unforgivable conceptualizations</p>
<p>permutation
encouraging</p>
<p>augmentation
recirculation questionnaire neurotransmitters
reconfigurable</p>
<p>uncontainable portraiture</p>
<p>boundaries
instantaneously
 unrecognizable
multidimensional
gelatinous</p>
<p> copulative manoeuvrings</p>
<p>cauliflower unavoidable</p>
<p>unsportsmanlike duodecimal</p>
<p>sequoias </p>
<p>customizable semiautomatic urogenital nonintellectual ejaculation self-regulation</p>
<p>automatized reputation perambulations</p>
<p>unforgivable ultraviolet heterosexuality</p>
<p>authoritative unapologetic filamentous Beauvoir</p>
<p>continuable pulverization</p>
<p>Australopithecus unseaworthiness</p>
<p>mendaciously questionable audiometers</p>
<p>mousetrapping 
unmentionable
fountainheads
malnourished</p>
<p>conceptualize nonintellectuals </p>
<p>uncontainable lasciviousness</p>
<p>ulceration superordinate</p>
<p>daguerreotyping  speculations</p>
<p>outmaneuvering exclusionary authentication </p>
<p>unexceptional purgatories</p>
<p>ultraconservative packinghouse </p>
<p>housewarming documentaries</p>
<p>unrecognizable Mozambique</p>
<p>unnoticeable eudaimonia </p>
<p>subcontinental encrustation revolutionaries</p>
<p>uneconomically undemocratic </p>
<p>reputations aeronautic </p>
 <p>superexponential housemaid questionnaires</p>
 <p>regulations reputations jailhouse </p>
 <p>delusional atrociousness overparticular</p>
<p>spaciousness anxiousness  </p>
<p>unpoetical euphoria, eunoia</p>
<p>unquestionable instantaneous </p>
<p>unobtainable pandemonium harmoniousness </p>
<p>flirtatiousness undiagnosable </p>
<p>milquetoasts overpopulating</p>
<p>unauthorized uncomplicated miraculousness</p>
<p>counterbalancing unconventional</p>
<p>interocular intercommunicating</p>
<p>unreasoning authoritatively </p>
<p>unproblematic audiotapes </p>
<p>miscellaneous gregariousness popularized</p>
<p>undiagnosed mountainside</p>
<p>emasculation liquefaction discourages </p>
<p>unexceptionable superexponential  </p>
<p>somersaulting telecommunication</p>
<p>encouragingly sacrilegious</p>
<p>outpatients overambitious</p>
<p>undomesticated outspreading rambunctiousness </p>
<p>overqualified crematorium </p>
<p>facetious enumeration putrefaction sequestration expostulation</p>
<p>preauthorize recalculations uncoordinated nonresidual</p>
<p>unmodifiable telecommunications</p>
<p>countervail pasteurization </p>
<p>undemocratic
nonequivalent quaternions</p>
<p>bougainvillea</p>
<p>instrumentation
unsanctioned</p>
<p>enunciation
reauthorizing</p>
<p>unexceptionally discouraged autobiographer</p>
<p>unincorporated perspicacious republication</p>
<p>overambitious neurotransmitter</p>
<p>elocutionary pneumonia</p>
<p>auspiciousness
sequestrations
occupancies
refutations</p>
<p>fountained grandiloquence</p>
<p>hallucinogenics contextualizing hippopotamuses </p>
<p>ejaculations evolutionary auditioned</p>
<p>tenacious intercommunicated odalisque</p>
<p>nonpunishable nucleation</p>
<p>cauliflowers stegosauri multimilionaires</p>
<p>denudation
reacquisition
rheumatoid</p>
<p>overstimulated
unprofessional</p>
<p>uncooperative
nonumericals</p>
<p>perturbation
unconscionable
excommunicate</p>
<p>communicativeness accoutering</p>
<p>consanguineous revaluation</p>
<p>beautification rejuvenation graciousness vivaciousness</p>
<p>discombobulates radionuclide emulation</p>
<p>unintentionally unorganized</p>
<p>maliciousness counterclaims</p>
<p>precautionary menstruation</p>
<p>praseodymium revaluation</p>
<p>intermolecular recalculation fractiousness</p>
<p>nefariousness outdistance</p>
<p>loudhailer concubinage</p>
<p>chemotherapeutic documentation</p>
<p>neutralization audiometer undercoating</p>
<p>unconstrained pedagoguing</p>
<p>expostulating
perambulation unfashionable</p>
<p>Aurelio Ecuadorians Beaujolais Cointreau Austronesian Hermaphroditus Aureomycin Luxembourgian
Belorusians Barquisimeto</p>
<p>neurological
automobiles</p>
<p>audiophile
fecundation</p>
<p>insupportable tourmaline supersaturation</p>
<p>subprofessional unmentionables</p>
<p>neurotically popularize conceptualization overenthusiastic </p>
<p>equivocating inconsequentialy</p>
<p>unappropriated institutionalized</p>
<p>repopulating sanctimoniousness </p>
<p>grandiloquent
counterrevolutionary</p>
<p>undervaluation devaluations efficacious contagiousness</p>
<p>uninformatively counteractive dehumanization overstimulates</p>
<p>auspiciousness insouciance pugnaciousness</p>
<p>obituaries education</p>
<p>equipartition evaluational unparodied</p>
<p>gubernatorial superannuation</p>
<p>discountable supplementation</p>
<p>disadvantageously
uncontaminated supersonically</p>
<p>subpoenaing orbiculares adventitiously encrustations</p>
<p>nonprejudicial undemonstratively magniloquent</p>
<p>malfunctioned emulsification recapitulation discontinuances continuances</p>
<p>carnivorousness 
vituperation</p>
<p>veraciously
demodulating</p>
<p>unconsolidated
preoccupation</p>
<p>ostentatiously
intercommunication
accentuation 
eructation</p>
<p>unexceptionably
nonumerical numerations</p>
<p>equation
fluoridate</p>
<p>argumentation
sequestrations</p>
<p>bougainvilleas</p>
<p>businesswoman depressurization</p>
<p>inoculates
deregulation
jalousie
perturbations</p>
<p>vicariousness unaccomplished</p>
<p>discountenanced
exhumations
auctioneer 
outpatients
praseodymium
uncongenial</p>
<p>malnourishment multifariousness authentications incommensurable  </p>
<p>neurologically unassociated denunciations</p>
<p>repudiator
extenuation
genitourinary</p>
<p>automatize avariciousness</p>
<p>congruential uncommunicative rapaciousness</p>
<p>precarious simultaneous</p>
<p>reinoculated intravenously</p>
<p>encapsulations
underestimation</p>
<p>inquorate refutations</p>
<p>abstemiously unnoticeable</p>
<p>mensuration
automotive
uncolimated</p>
<p>equinoctial
judicatories
overpopulation</p>
<p>cautioned unconventionally</p>
<p>exhumations
counteracting</p>
<p>perpetuation 
equivocations</p>
<p>depopulating
expurgation</p>
<p>preoccupations</p>
<p>subordinated remuneration</p>
<p>voluptuaries
excommunications mountaineered</p>
<p>authenticator
coinsurance</p>
<p>underspecification pertinaciously </p>
<p>unequivocally equivocally</p>
<p>equitation exudation peculation deputations</p>
<p>equalization autocorrelation</p>
<p>coleaguing autocracies</p>
<p>capriciousness vexatiously</p>
<p>reunification resuscitation</p>
<p>conceptualizes
communicative</p>
<p>nonautomotive auctioned revaluations</p>
<p>attenuation underpopulation unsatisfactoriness</p>
<p>countermanding questionnaires</p>
<p>authorize  speculation</p>
<p>questionably laboriousness</p>
<p>modularized contextualization </p>                                                      
		</section>	
</article>

app/views/poem/birds.html.erb
<%= provide(:title, "Darkling I listen") %>
<%= render "layouts/omphalos" %>
<article class="close-the-poetic-loop row">
	<section class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-5 col-xs-8 col-xs-offset-2">
	<p>
		It goes without saying that the poetic tradition of birdsong is immense. But still I said it. The pervasive similes of lyricism - or even poetry - as being alike birdsong have nearly made the terms synonymous. But what are the sounds that birds actually make? This poem recontextualizes Roger Peterson's vocal transcriptions of bird sounds from his definitive guide, <a href="http://www.amazon.com/Field-Guide-Western-Birds-Completely/dp/B005UVSA88"><b>A Field Guide to Western Birds: A Completely New Guide to Field Marks of All Species Found in North America West of the 100th Meridian and North of Mexico</b></a>. If anything, in light of postmodern and contemporary poetics, Peterson's nuanced attentiveness to sonic variance actually girts the age old metaphor, challenging the poetics of today to even attempt to express themselves in any of these surprising and inventive ways. I want a prosody of whinnying, a poetics of high-pitched cooing, a poetry of <em>kah-la-a-luk</em>. <span style = "font-size: 0.85em;">Note, also note the homonym shared between Peterson's use of "note", and that of say, Vanessa Place and Rob Fitterman in <a href="http://www.uglyducklingpresse.org/catalog/browse/item/?pubID=20"><b>Notes on Conceptualisms</b></a> or Felix Bernstein in his <a href="http://www.thevolta.org/ewc41-fbernstein-p1.html"><b>Notes on Post-conceptual Poetry</b></a>. Hmmm...</span>
	</p>
	</section>
</article>
<section class="row">
 	<section class="col-md-6 col-md-offset-5 col-sm-offset-5 col-xs-offset-5 bird-title">
       <h1><b>Bird Songs</b></h1>
	</section> 
</section>
<!-- The Poem -->
<article class="darklinglistening row">
	<section class="col-md-6 col-md-offset-4">
	<p><b>Voice:</b> When flying, a repeated <em>kwuk</em>. In Arctic, falsetto wails.</p>
	<p><b>Voice:</b> In summer, falsetto wails, weird yodeling, maniacal quavering laugher; at night, <br> a tremulous <em>ha-oo-oo</em>. In flight, a barking <em>kwuk</em>. Usually silent in winter.
	<p><b>Voice:</b> <em>Kuk-kuk-cow-cow-cow-cowp-cowp;</em> also whinnying</p>
	<p><b>Voice:</b> A sharp <em>keer, keer</em> or a lower <em>kee</em>.</p>
	<p><b>Voice:</b> A mellow, high-pitched cooing: <em>woo-ho, woo-woo, woo-ho</em>.</p>
	<p><b>Voice:</b> High pitched tootling, <em>kah-lah-a-luk</em>, in chorus. </p>
	<p><b>Voice:</b> A deep, musical honking or barking, <em>ka-ronk</em> or <em>ka-lunk</em></p>
	<p><b>Voice:</b> A squeeling slurred whistle, <em>ka-whee-oo</em></p>
	<p><b>Voice:</b> Male has a low <em>bek</em>; a whistling call. Female quacks.</p>
	<p><b>Voice:</b> Male, <em>yeeb</em>; a low <em>kwek</em>. Female, boisterous quacking.</p>
	<p><b>Voice:</b> Male, a double-toned whistle: <em>prrip prrip</em>; wheezt notes. Female, a low <em>quack</em>.</p>
	<p><b>Voice:</b> The courting male utters a low crooning phrase; the female makes grunting croaks. </p>
	<p><b>Voice:</b> Male, a moaning <em>ow-ooo-urr</em>. Female, a grating <em>kor-r-r</em>.</p>
	<p><b>Voice:</b> Talkative; a musical <em>ow-owdle-ow</em>, or <em>owl-omelet</em>.</p>
	<p><b>Voice:</b> Male in courtship, cooing notes. Female <em>quacks</em>, etc.</p>
	<p><b>Voice:</b> Male, a harsh catlike <em>meow</em>; a deep purr. Female <em>quacks</em>.</p>
	<p><b>Voice:</b> Courting male, a sputtering <em>chick-ik-ik-ik-k-k-k-kurrrr</em>.</p>
	<p><b>Voice:</b> A grating <em> kuk-kuk-kuk-kuk; kakakakakaka</em>, etc.; also a measured <em>ka ha, haha</em>; various cackles, croaks.</p>
	<p><b>Voice:</b> A croaking <em>kr-r-ruk</em>, repeated; a froglike <em>kup</em>; also <em>kek, kek, kek</em> and load, complaining, henlike notes.</p>
	<p><b>Voice:</b> Soft, short, barking notes. Also <em>kaup kaup</em>.</p>
	<p><b>Voice:</b> Deep harsh croaks: <em>Frahnk, frahnk, frahnk</em>.</p>
	<p><b>Voice:</b> Note, a thin, charp <em>chip</em>; distinctive. </p>
	<p><b>Voice:</b> Song, a low, muted <em>coo-coo-coo</em>, heard in the marsh.
	<p><b>Voice:</b> A rasping <em>scaip</em>. Song, a measured <em>chip-a, chip-a, chip-a,</em> etc. In high arial display, a winnowing <em>huhuhuhuhuhuhu</em>.
	<p><b>Voice:</b> A mellow, whistled <em>kip-ip-ip-ip</em>, often heard at night. Song, weird windy whistles: <em>whoooleeeeee, wheeloooooooooo</em>.</p>
	<p><b>Voice:</b> A mouselike <em>jeet</em>, like two flint pebbles scraping.</p>
	<p><b>Voice:</b> Usually silent. Occasionally a harsh <em>churrr</em> or <em>chee-ur</em>. </p>
	<p><b>Voice:</b> Drumming of male suggests a distant motor starting up. Muffled thumping starts slowly, accelerating into a whir: <em>Bup . . . bup . . . bup . . . bup . . bup,bup,up,r-rrrrrr.</em></p>
	<p><b>Voice:</b> Deep raucous calls, <em>go-out, go-out</em>. Male, a staccato crow, <em>kwow, kwow, tobacco, tobacco</em> etc., or <em>go-back, go-back</em>.</p>
	<p><b>Voice:</b> Song, in hovering flight and quivering descent, ecstatic and bubbling: starts with low, reedy notes and rollicks upward. Flight note, a clear <em>pink</em>, often heard overhead in migration.</p>
	<p><b>Voice:</b> Song, a rolling <em>chiddle-chiddle-chiddle, turtle-turtle</em>, last notes dropping; or <em>sweeter-sweeter-sweeter, sugar-sugar</em>.</p>
	<p><b>Voice:</b> Song, a husky, lazy <em>zur, zur, zur, zreee</em>, or <em>beer, beer, beer, bree</em> (ending higher).</p>
	<p><b>Voice:</b> A lisping, dreamy <em>zoo zee zoo zoo zee</em> or <em>zee zee zee zee zoo zee;</em> the <em>zee</em> notes on same pitch, the <em>zoo</em> notes lower.</p>
	<p><b>Voice:</b> Starling-like; repeated phrases. An accomplished mimic.</p>
	<p><b>Voice:</b> Song, liquid, breezy, ethereal; wheeling downward: <em>vee-ur, vee-ur, veer, veer.</em></p>
	<p><b>Voice:</b> A long, eerie, quavering, whistled note, followed, after a pause, by one on a lower pitch or higher pitch. A liquid <em>chup</em>.</p>
	<p><b>Voice:</b> A monotonous <em>chuh-chuh-chuh-chuh</em>, etc., or <em>chug-chug-chug-chug-chug</em>, on one pitch, gaining rapidity; unbird-like.</p>
	<p><b>Voice:</b> A two- or three-syllabled chant. Variable; <em>tea-kettle, tea-kettle, tea kettle</em>, or <em>chirpity, chirpity, chirpity, chirp</em>.</p>
	<p><b>Voice:</b> A rough, querulous <em>wink? wink?</em> or <em>zhenk?</em></p>
	<p><b>Voice:</b> A high, penetrating <em>kee-zee'ick! kee-zee'ick!</em>. <p>
	<p><b>Voice:</b> <em>Whack-up, whack-up, whack-up,</em> or <em>ja-cob, ja-cob</em>. </p>
	<p><b>Voice:</b> A mournful, drawling whistle, slurring down, <em>peeur</em>.</p>
	<p><b>Voice:</b> Song, bright, loose and disjointed.</p>



	</section>
</article>

app/views/poem/index.html.erb
<% flash.each do |message_type, message | %>
        <%=content_tag(:div, message, class: "fade-out alert alert-#{message_type}", style: "display:inline-block") %>
        <% end %> 
<%= render 'long_poem' %>
<!-- BEGIN OTHERNESSES -->
<section class="col-md-6 col-sm-6 col-xs-6">
<!-- SVG CIRCLE -->
<section class = "the-center-cannot-hold text-center">
	<svg height="140" width="140" class = 'hvr-wobble-skew'>
	  <circle id = "periphery" class = "hvr-wobble-skew" cx="55" cy="50" r="40" stroke="#00DDFF" stroke-width="3" fill="white" />
	</svg>
</section>
<!-- BEGIN LINKS -->
<section class="links text-center">
<section class="row options">
	<article class="col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-6 col-xs-offset-3">
		<p class = "possible poetries">Poetries</p>
		<section class="poems row text-center">
			<%= link_to "luelttettsers", luelttettsers_url %>
			
			<%= link_to "RilK(e)ittler's Ninth Elegy", rilkittler_url %>
			
			<%= link_to "Self-Portrait in a Concave Mirror", selfportrait_path %>
			
			<%= link_to "Hot Network Questions", hotnetworkquestions_path %>
			
			<%= link_to "Bread", bread_path %>
			
			<%= link_to "Western Birds", birds_path %>
			
			<%= link_to "Artemis, Apollo", sunmoon_path %>

			<%= link_to "yoloy", yoloy_path %>

			<%= link_to "Case Study: B", casestudyb_path %>

			<%= link_to "spuilyie", spuilyie_path %>

			<%= link_to "groundbreaking unimportance", aeiou_path %>
		</section>
	</article>
</section>

<section class="row options">
	<article class="col-md-8 col-md-offset-2 essays col-sm-6 col-sm-offset-3 col-xs-6 col-xs-offset-3">
		<p class = "possible assays">Essays</p>
		<section class="essaytries text-cener">
			<%= link_to "It's Okay, We Can Just Check the Numbers Afterwards", checkthenumbersafter_path %>
		</section>
	</article>
</section>

<section class="row options">
	<article class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-12  about">
		<p class = "possible aboot">About</p>
		<section class="abbot text-left">
			<p>The poem on the left is a long poem in progress. In fact, you contributed the word <b><%= @new_word %></b> to it just now. The poem accrues a new and randomized word from the English language each time this webpage is accessed or reloaded. Please share this page on sites with webscraping robots so that we can create a great long poem together, and without much effort. </p>
			<br>
			<p><em>~ Write a poem just by refreshing your browser ~</em></p>
		</section>
	</article>
</section>
</section>

</section>